### ISSUE TITLE
The character encoding declaration of the framed HTML not found

### ISSUE THREAD

**Issue by bkd** [kogmbh/ViewerJS#112]
The character encoding declaration of the framed HTML document was not found when prescanning the first 1024 bytes of the file. When viewed without the document framing it, the page will reload automatically. The encoding declaration needs to be moved to be within the first 1024 bytes of the file.

I get this when I convert a word document from openoffice/libreoffice to pdf and then try to view the file..

**Comment by kossebau** [comment]
Thanks for reporting. This is a mistake independent of the viewed file, `ViewerJS/index.html` needs the `<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>` to be closer to the begin.

Will be fixed in the upcoming ViewerJS release end of this month. Until then you can fix this in your local copy by moving all the comment at the begin behind the line with the cited `<meta>` element.

**Comment by kossebau** [comment]
Fixed with today's ViewerJS 0.5.5 release.
