### ISSUE TITLE
How to set default zoom level to page-width

### ISSUE THREAD

**Issue by abelkbil** [kogmbh/ViewerJS#129]
i love ViewerJS.
How to set default zoom level to "page-width"

pdf.js support something like  defaultZoomValue:page-width

How can we do it
<iframe src = "<?php echo $pdf_url;?>" width='1200' height='1200' allowfullscreen webkitallowfullscreen defaultZoomValue:page-width></iframe>

**Comment by kossebau** [comment]
> i love ViewerJS.

Thanks :)

> How to set default zoom level to "page-width"

Since ViewerJS 0.5.5 this can be done by passing a parameter "zoom" to ViewerJS, e.g.
        /ViewerJS/?zoom=page-width#/test/pdf/do.pdf

So insert ?zoom=page-width right before the #.

Documentation still missing from ViewerJS(.org), should be added every other day.

See some info already here: https://open.nlnet.nl/pipermail/webodf/2015-February/000169.html

**Comment by abelkbil** [comment]
Very Thank you @kossebau
