### ISSUE TITLE
Help on getting run on glasfish sever...

### ISSUE THREAD

**Issue by Baze985** [kogmbh/ViewerJS#133]
Hi,

I tried to run it under glassfish with no success. Where exectly I need to put ViewerJS folder?
I almost try in any location under glassfish root folder but I never get it running..
http://localhost:8080/ViewerJS/ its never found ?!

Tnx for the help.

**Comment by kossebau** [comment]
Hi. You can put the ViewerJS folder where ever you like inside the webserver root folder. All the files of ViewerJS are delivered as static files just like any other HTML, CSS, JS, PNG etc. files. So that should not be your problem.

If just using `ViewerJS/` results in "not found", try also `ViewerJS/index.html`. The examples/instructions on viewerjs.org rely on most webservers forwarding to `index.html` with just a folder name given.
See also #81. Adding a FAQ page also noting such problems to viewerjs.org is planned, just not yet executed...

Please tell if using explicitely `ViewerJS/index.html` solved it for you.

**Comment by Baze985** [comment]
THx for the replay.

Here is what needs to be done.

The files must be available for the webserver to serve it.
If webserverbase url is used then this must be available for the root of the webserver.

Under tomcat: tomcatinstaldir/.../webapps/ROOT/ViewerJS/   where it needs to bre created/copied
under glassfish: glassfishinstaldir/../domains/domainame(domain1 default)/docroot/ViewerJS/  where it needs to bre created/copied

then for the usage: /ViewerJS/#../webappfromwhereitsserved/somestaticdir/ohm2013.odp

I have one question: is it capable of opening MS office files? I tried with .xlsx but its not working for me, no exp but nothing is displayed....

**Comment by kossebau** [comment]
So it works now for you? Good :) Thanks for the explanation how you made it work, sounds correct, and might help others facing the same problem.

> is it capable of opening MS office files?

Citing viewerjs.org:
"ViewerJS can already natively show both PDF files and many types of Office files stored in OpenDocument Format, the open standard for office documents."

So the answer is no, there is no plugin currently which support MS formats. We would happily integrate such a plugin, if someone writes one.
A workaround could be to convert such files to PDF on the fly on the server using e.g. a head-less LibreOffice installation. That has been done already. Don't know ready-made code for that, but one could take inspiration from  https://github.com/owncloud/format-filter-server

Given problem solved and answer given, closing this issue now for proper housekeeping, please reopen if there are remaining related issues.
