### ISSUE TITLE
friendly url

### ISSUE THREAD

**Issue by JaviIndian** [kogmbh/ViewerJS#170]
Hi, I 'm implementing viewer.js on my website.
I would like to know if it is possible to clean the url , so that it appears as friendly url .
I've been testing with RewriteRule in htaccess but I can not do it.
I guess it may be because the target file is not php
I hope you can help
Thanks and regards

**Comment by chrilith** [comment]
Hello,

It is not possible. It is url-hash-based, The hash is a client element and cannot be set on the server even with url rewriting.

**Comment by leenaars** [comment]
However, by cleverly naming your files and folders you can go a long way to making things more user friendly/shorter - using the same tactics as minifier scripts do. E.g. if your site is example com:

  * rename the folder "ViewerJS" to "V" so you can have the shortest possible reference 
  * your file names are irrelevant to ViewerJS, so instead of "LongDocumentName.odt" you can just use "a.odt"

So that would leave you with URL's like:

https://example.com/V/?a.odt

Friendly enough?

**Comment by JaviIndian** [comment]
OK. Thank you very much for the answers.
I will change the name of folders and files, as Ieenaars says .
Thanks again
