### ISSUE TITLE
PDF bigger than 100kb

### ISSUE THREAD

**Issue by GaboDot** [kogmbh/ViewerJS#94]
I have tested this viewer with pdf files smaller than 100kb and everything it's ok, the problem is when this files are bigger than 100kb all the pages show blank and never loads the document, I hope someone can help me.

http://gabo.herobo.com/prueba/

**Comment by zenzei** [comment]
Hi @g4b0-88 , can you share how you resolved this issue? I'm having the same problem when streaming a file instead of using static file.

**Comment by g4b0-88** [comment]
Hi @zenzei 
As I mentioned on the preovious comments, I had to use the full PDF.js to stream large files, also I found some issues when rendering color images, I don't know if actually the viewer works better, it has been more than a year since this. 
Also I remember that I was asked to disable download and print functions so on viewer I coulnd't find how to do this, but in PDF.js I found the needed code to achieve that.
An extra comment is that you can create low-size profiles on Acrobat DC to optimize your files and make them smaller without lossing quality or readibility.

Here the links for the PDF.js
http://mozilla.github.io/pdf.js/

Documentation:
https://github.com/mozilla/pdf.js/

Hope this helps.
